include:
  - redbox-backend/docker-compose.yml

services:
  streamlit-app:
    image: redbox-streamlit-app:latest
    build:
      context: .
      dockerfile: ./streamlit_app/Dockerfile
      args:
        - EMBEDDING_MODEL=${EMBEDDING_MODEL:-}
    env_file:
      - .env
    ports:
      - 8501:8501
    volumes:
      - ./data:/app/data:Z
      - ./streamlit_app:/app/streamlit_app/
    depends_on:
      - elasticsearch
      - minio
    links:
      - elasticsearch
      - minio
    networks:
      - redbox-app-network
